<a href="https://colab.research.google.com/github/DrSubbiah/6.Python/blob/main/4_PANDAS_DF_StepbyStep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color = darkred> PANDAS Major Functions for Data Science

<font color = 'darkblue'>Import libraries **pandas as pd** and **numpy as np**

1. <font color = 'darkgreen'>**Loading a data set in csv (as a DataFrame,df)**

      read_csv()

1. <font color = 'darkgreen'>**Know the structure**

      df.shape (df.size, optional,dimension for rectangular data is always 2)

1. <font color = 'darkgreen'>**Know the names of columns**

      df.columns

1. <font color = 'darkgreen'>**To view few rows**

      * df
      * df.head()
      * df.tail()
      
        - inside ( ) type any positive integer to get as many rows

1. <font color = 'darkgreen'>**Know the structure of DF (nature of variables)**

      df. dtypes (df.info(verbose=True) is optional)

    Major Data types

      * float64
      * int64
      * category
      * object

1. <font color = 'darkgreen'>**Change the nature of a variable**

      df['column'] = df['column'].astype( )

1. <font color = 'darkgreen'>**Know the presence of *NA* or *NaN***
      * pd.isna(df)
      * pd.isnull(df)
      * df.isna()
      * df.isnull()
      
  To know the row / column indices - presence of NA
      * np.where(pd.isna(ecg_data))

  Row / column indices - presence of NA as a DF
      * pd.DataFrame(list( ),index=["R","C"]).T

        *R and C are column names and T is to transpose*

1. <font color = 'darkgreen'>**To *sort* by columns**
      
      df.sort_values(by=['C1','C2],axis=0, ascending=True, na_position= ‘last’)

1. <font color = 'darkgreen'>**To *sort* by rows**      
      
      df.sort_values(by=index values,axis=1, ascending=True, na_position= ‘last’), index values are row names

1. <font color = 'darkgreen'>**To *change* the nature of a variable**
      
      df.select_dtypes(' ') - inside (' ') type the required nature (like float64)

1. <font color = 'darkgreen'>**To *count* based on distinct value (numeric) or distinct level of a categorical variable**

      df.C.value_counts() - C is the name of the column (variable) to count

1. <font color = 'darkgreen'>**To *replace* a value**
      
      df.replace(existing value,new value)

1. <font color = 'darkgreen'>**To *create* a new variable**

      df['new variable'] = any suitable operations (changes can be made in a same variable, instead of *new variable* use the existing variable name)

1. <font color = 'darkgreen'>**Conditionally create a column (variable)**  

### using if, elif, else

for i in df.index:
  
    if (df.loc[i,"column"] condition 2):
      df.loc[i,'new column']=value 1
    elif((df.loc[i,"column"] condition 2) & (df.loc[i,"new_column"] condition 3)):
      df.loc[i,'new_column']=value 2
    else:
      df.loc[i,'new column']= value 3

### Using conditions and choices and np.select

conditions = [(df["column"].condition 1),
    (df["column"].condition 2 & df["column"].condition 3),
    (df["column"].condition 4]
    
choices = [value 1, value 2]
    
df["new column"] = np.select(conditions, choices)


### Using np.where

    df['new column']=np.where((df["column"]condition 1),value 1,

                    np.where((df['column'] condition 2) & (df['column'] condition 3), value 2,

                   'value 3'))

### Remark - while  adding columns conditionally

<font color="green"> condition 1,2,3... may be the required logical (lt(10), ge(10), == etc) expressions the esixting column would satisfy

<font color="blue">Value 1, 2.. are corresponding numeric or string values the new column will assume  (nmeric or string uniformly)

<font color="orange">df["new column"].value_counts(sort=False) to get the counts as per the order of definition

1. <font color = 'darkgreen'>**Subset / Slicing /Filtering**
      
      d1[1,2] - First row and 3rd column

      d1.iloc[0:2,] - first two rows and all columns

      d1.iloc[2:,] - all the rows from third row and all columns

      d1.iloc[:,1] - second column and all rows

      ### Conditional (usage of "&", "|" (and , or))
      
      df.loc[(df['var'] >= ) & (df['var'] < )| (df['var]== )]

1. <font color = 'darkgreen'>**Group by**

      df.group_by(['var']) followed by desired averages or other computations

      df.group_by(['var1','var2]) ----- for more than two variables

1. <font color = 'darkgreen'>**Drop a column / row**

      df=df.drop(columns=["var1","var2])
      
      df=df.drop(index=[1,2,3]) - row indices
      
      df=df.frop(columns=coldrop,index = rowdrop) - coldrop / rowdrop are list of columns / rows to drop



## Data Analysis

<font color = 'darkgreen'>**Summary**

* df.describe() ----- for the whole data set, numeric variable

* df['var'].describe() ------ for a specific variable

* df.groupby(['var1','var2']).describe()

  * Other quantities - median, min, max, quantiles can be computed

    * For eg, df.groupby(['var1','var2']).quantile(p), where 0 < p < 1

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
ecg_data=pd.read_csv("/content/drive/MyDrive/echocardiogram.csv")

In [ ]:
ecg_data.ndim, ecg_data.size, ecg_data.shape

(2, 1716, (132, 13))

In [ ]:
ecg_data.iloc[0,0]#ecg_data.iloc[:,2:5] #ecg_data.iloc[0:2,]

11.0

In [ ]:
aa=ecg_data.loc[ecg_data['age']>50].groupby(["alive"])['age'].mean()

In [ ]:
aa

alive
0    63.265306
1    67.355375
2    62.000000
Name: age, dtype: float64

In [ ]:
ecg_data.head(5)

,survival,still_alive,age,pericardial,fractional,epss,lvdd,wall,wall_1,mult,name,group,alive
0,11.0,0,71.0,0,0.260,9.000,4.600,14.0,1.00,1.000,name,1.0,0
1,19.0,0,72.0,0,0.380,6.000,4.100,14.0,1.70,0.588,name,1.0,0
2,16.0,0,55.0,0,0.260,4.000,3.420,14.0,1.00,1.000,name,1.0,0
3,57.0,0,60.0,0,0.253,12.062,4.603,16.0,1.45,0.788,name,1.0,0
4,19.0,1,57.0,0,0.160,22.000,5.750,18.0,2.25,0.571,name,1.0,0

In [ ]:
ecg_data.dtypes #ecg_data.info(verbose=True) - optional

survival       float64
still_alive      int64
age            float64
pericardial      int64
fractional     float64
epss           float64
lvdd           float64
wall           float64
wall_1         float64
mult           float64
name            object
group          float64
alive           object
dtype: object

In [ ]:
di=['age','wall','group']
#ecg_data.drop(index = di)
ecg_data.drop(columns=di,index = [0,1,2])

,survival,still_alive,pericardial,fractional,epss,lvdd,wall_1,mult,name,alive
3,57.0,0,0,0.253,12.062,4.603,1.450,0.788,name,0
4,19.0,1,0,0.160,22.000,5.750,2.250,0.571,name,0
5,26.0,0,0,0.260,5.000,4.310,1.000,0.857,name,0
6,13.0,0,0,0.230,31.000,5.430,1.875,0.857,name,0
7,50.0,0,0,0.330,8.000,5.250,1.000,1.000,name,0
...,...,...,...,...,...,...,...,...,...,...
127,7.5,1,0,0.240,12.900,4.720,1.000,0.857,name,NaN
128,41.0,0,0,0.280,5.400,5.470,1.100,0.714,name,NaN
129,36.0,0,0,0.200,7.000,5.050,1.210,0.857,name,NaN
130,22.0,0,0,0.140,16.100,4.360,1.360,0.786,name,NaN
131,20.0,0,0,0.150,0.000,4.510,1.409,0.786,name,NaN

In [ ]:
ecg_data.columns

In [ ]:
ecg_data['alive']=ecg_data['alive'].astype('category')
ecg_data['still_alive']=ecg_data['still_alive'].astype('category')
ecg_data['pericardial']=ecg_data['pericardial'].astype('category')
#ecg_data=ecg_data.drop(columns=["group"])

In [ ]:
#pd.isna(ecg_data)
#pd.isnull(ecg_data)
#ecg_data.isna()
#ecg_data.isnull()

#optianlly we can name the NA as "na" or "NaN"
#ecg_data=ecg_data.replace(np.NaN,"na")
np.where(pd.isna(ecg_data))

(array([ 24,  25,  27,  27,  27,  28,  28,  28,  28,  28,  28,  30,  30,
         31,  32,  32,  32,  33,  34,  34,  36,  36,  37,  38,  39,  39,
         39,  43,  44,  45,  45,  45,  46,  46,  48,  48,  48,  49,  49,
         49,  49,  49,  49,  50,  50,  50,  51,  51,  52,  59,  59,  61,
         61,  63,  64,  66,  74,  76,  79,  80,  82,  84,  84,  84,  85,
         86,  87,  89,  90,  91,  93,  94,  95,  97, 100, 100, 101, 103,
        107, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
        122, 123, 124, 125, 126, 127, 128, 129, 130, 131]),
 array([11, 11,  4,  6, 11,  4,  5,  6,  7,  9, 11,  5, 11, 11,  4,  6, 11,
        11,  4,  6,  4,  5,  6,  5,  7,  9, 11,  5, 11,  5,  6, 11,  5,  6,
         4,  5,  6,  0,  4,  5,  6,  7,  8,  7,  8,  9,  5,  6, 11,  5, 11,
         5, 11, 11, 11, 11, 11, 11, 11, 11, 11,  4,  5,  6, 11, 11, 11, 11,
        11, 11, 11,  0, 11, 11,  5, 11,  5, 11, 11, 11, 11, 11, 11, 11, 11,
        11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11]))

In [ ]:
na1=np.where(pd.isnull(ecg_data))
#na1=pd.DataFrame(np.where(pd.isna(ecg_data)))
np.array(na1).size
na2=pd.DataFrame(list(na1),index=['R','C']).T
na2.sort_values(by=['C']) #.T.C.value_counts()

       R   C
72    94   0
37    49   0
34    48   4
14    32   4
20    36   4
..   ...  ..
65    85  12
60    80  12
59    79  12
85   112  12
123  131  12

[124 rows x 2 columns]

In [ ]:
na2.C.value_counts()

12    56
11    23
5     15
6     11
4      8
7      4
9      3
0      2
8      2
Name: C, dtype: int64

In [ ]:
ecg_data.fillna(ecg_data.mean)

In [ ]:
ecg_data.select_dtypes('object').columns

In [ ]:
d1=ecg_data.select_dtypes('float64')
#d1['survival'].fillna(d1['survival'].mean(),inplace=True)
#d1=d1.fillna(d1.mean, inplace = True)
#d1=d1.drop(columns=["group"])
d2=d1.fillna(d1.mean, inplace = True)
#d2=pd.DataFrame(d1)
#d2['survival']=d2['survival'].astype(dtype='Float64')

#d2=pd.to_numeric(d2['survival'], errors='coerce')
##ecg_data['pericardial']=ecg_data['pericardial'].astype('category')

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:5176: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

In [ ]:
#d1.dtypes,
type(d1),d1

(NoneType, None)

In [ ]:
#d1.replace(d1['survival'][0:],12)
#pd.Series(d1['survival'])>12
np.where(d1['survival']==11)

In [ ]:
ecg_data.loc[(ecg_data['age'] >= 50) & (ecg_data['survival'] <= 35)]

,survival,still_alive,age,pericardial,fractional,epss,lvdd,wall,wall_1,mult,name,group,alive
0,11.0,0,71.0,0,0.26,9.0,4.60,14.0,1.000,1.000,name,1.0,0
1,19.0,0,72.0,0,0.38,6.0,4.10,14.0,1.700,0.588,name,1.0,0
2,16.0,0,55.0,0,0.26,4.0,3.42,14.0,1.000,1.000,name,1.0,0
4,19.0,1,57.0,0,0.16,22.0,5.75,18.0,2.250,0.571,name,1.0,0
5,26.0,0,68.0,0,0.26,5.0,4.31,12.0,1.000,0.857,name,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,17.0,0,55.0,0,0.09,6.8,4.96,13.0,1.080,0.857,name,NaN,NaN
126,21.0,0,61.0,0,0.14,25.5,5.16,14.0,1.270,0.786,name,NaN,NaN
127,7.5,1,64.0,0,0.24,12.9,4.72,12.0,1.000,0.857,name,NaN,NaN
130,22.0,0,57.0,0,0.14,16.1,4.36,15.0,1.360,0.786,name,NaN,NaN
131,20.0,0,62.0,0,0.15,0.0,4.51,15.5,1.409,0.786,name,NaN,NaN